# Generated by Django 5.1.6 on 2025-03-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='V_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('book_number', models.CharField(max_length=15)),
                ('author', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('print_time', models.DateTimeField()),
                ('field', models.CharField(max_length=50)),
                ('time', models.TimeField()),
            ],
        ),
    ]
