# Generated by Django 5.1.6 on 2025-03-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('mag_number', models.CharField(max_length=15)),
                ('author_1', models.CharField(max_length=100)),
                ('author_2', models.CharField(max_length=100)),
                ('author_3', models.CharField(max_length=100)),
                ('author_4', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('print_time', models.DateTimeField()),
            ],
        ),
    ]
